Fix #10 #11 #12
zenith-hacks/zenith pull request #14
Opened 2024-09-10 00:42 UTC by hnasheralneam

Moves all content over from the old site. The next time I get some down time, I'll make the teams page. Also, I'm very very sorry for the inline styles, but I've got no idea how svelte works and thus could not find the stylesheets.

2024-09-10 14:10 UTC, iamawatermelo commented
Styles are at the bottom of the page. I'll just fix it myself and merge.

2024-09-10 14:35 UTC, hnasheralneam commented
Thanks for fixing it! I'll make sure to put them in the right place next time.

2024-09-10 14:36 UTC, iamawatermelo requested changes
This PR contains many duplicated images and changes too many things, including styling which should be coordinated with me first. Please read the README. Try find SVG logos for our sponsors---I've asked everyone to get in contact with their sponsor contacts to get this.

2024-09-10 14:36 UTC, iamawatermelo commented on src/routes/code-of-conduct/+page.svelte
This file is already in another PR

2024-09-10 14:36 UTC, iamawatermelo commented on src/routes/+page.svelte
> +    <div><img class="image-box" src="https://cdn.britannica.com/41/196341-050-6B55B7E7/solar-eclipse-moon-sun-space-astronomy.jpg" alt="A photo of a solar eclipse"></div>
Do not hotlink to images + accessibility: screen readers already announce that it is an image

2024-09-10 14:36 UTC, iamawatermelo commented on src/routes/+layout.svelte
> +
Why was this moved?

2024-09-10 14:36 UTC, iamawatermelo commented on src/routes/+layout.svelte
> +            <span style="color: #999">Threads</span> <a href='https://threads.net/@zenith_hacks'>@zenith_hacks</a>
Please use the same style as everything else

2024-09-10 14:36 UTC, iamawatermelo commented on src/routes/+page.svelte
> +        A hackathon is a social event focused on coding where teenagers come together to learn, build, and share their results with others!
Please format

2024-09-10 14:36 UTC, iamawatermelo commented on src/lib/logos/desmos-on-light.png
We aren't sponsored by the Desmos Foundation.

2024-09-10 14:36 UTC, iamawatermelo commented on src/lib/logos/1password-on-light.svg
This file already exists.

2024-09-10 14:36 UTC, iamawatermelo commented on src/lib/logos/codeforcause.png
This file already exists.

2024-09-10 14:36 UTC, iamawatermelo commented on src/lib/logos/disney-on-light.svg
This file already exists.

2024-09-10 14:36 UTC, iamawatermelo commented on src/lib/logos/google.png
We aren't sponsored by Google.

2024-09-10 14:36 UTC, iamawatermelo commented on src/lib/logos/interview-buddy.png
Where is this on the sponsorship spreadsheet?

2024-09-10 14:36 UTC, iamawatermelo commented on src/lib/logos/redbull.svg
This file already exists.

2024-09-10 16:06 UTC, hnasheralneam commented on src/routes/code-of-conduct/+page.svelte
Did not see it, sorry.

2024-09-10 16:07 UTC, hnasheralneam commented on src/routes/+page.svelte
> +    <div><img class="image-box" src="https://cdn.britannica.com/41/196341-050-6B55B7E7/solar-eclipse-moon-sun-space-astronomy.jpg" alt="A photo of a solar eclipse"></div>
I'll add the image to the project, alt text is still important to know what the image is about.

2024-09-10 16:08 UTC, hnasheralneam commented on src/routes/+layout.svelte
> +
I was attempting to put the footer links into clearer categories.

2024-09-10 16:09 UTC, hnasheralneam commented on src/routes/+layout.svelte
> +            <span style="color: #999">Threads</span> <a href='https://threads.net/@zenith_hacks'>@zenith_hacks</a>
All other footer links are using the same style, it makes it clear what part is the link, and it's easier to skim than a sentence description for each.

2024-09-10 16:10 UTC, hnasheralneam commented on src/routes/+page.svelte
> +        A hackathon is a social event focused on coding where teenagers come together to learn, build, and share their results with others!
Sorry, I'll try to configure the IDE to your style (2 chars spaces?) and format it.

2024-09-10 16:11 UTC, hnasheralneam commented on src/lib/logos/desmos-on-light.png
I just copied all the images over, I forgot to remove it. I only used the Desmos company logo in the sponsors section.

2024-09-10 16:11 UTC, hnasheralneam commented on src/lib/logos/1password-on-light.svg
Sorry, I'll remove all the extra image files.

2024-09-10 16:12 UTC, hnasheralneam commented on src/lib/logos/google.png
They offered us the location, and for now it seems like the main choice. We can change it if we settle on somewhere else.

2024-09-10 16:13 UTC, hnasheralneam commented on src/lib/logos/interview-buddy.png
Rushil told me to add it through the slack, I don't know if he added it to the sheet.

2024-09-10 16:19 UTC, hnasheralneam commented
We can't just not include sponsors because there is no SVG version of their logo currently available; the PNG logos work for now, and the .2 seconds they add to the page load seem like a fair price to pay for the support the companies are giving us.

2024-09-10 16:32 UTC, iamawatermelo commented
Alright. Please resolve all changes though, you've just marked them as resolved without doing anything...

2024-09-10 16:34 UTC, hnasheralneam commented
I've made (some of) the changes you asked for.

2024-09-11 18:23 UTC, hnasheralneam commented
@iamawatermelo I've resolved the conflicts, can you look at this again?

2024-09-12 16:58 UTC, closed without merging